#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=ring;size=6", "id=feet;size=1", "id=hands;size=1", "id=curio;size=3", "id=necklace;size=2"]

